# Generated by Django 4.1.7 on 2023-08-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkersMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserLogin', models.CharField(max_length=255)),
                ('ShortName', models.CharField(max_length=50)),
                ('UserPassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Workers_Main',
            },
        ),
    ]
